name       : eglexternalplatform
version    : 1.0
release    : 2
source     :
    - git|https://github.com/NVIDIA/eglexternalplatform : e3b182e3253f92bdbb03a71fdbd958bfb69cf3e3
license    : MIT
component  : programming.library
summary    : The EGLStream-based Wayland external platform
patterns   :
    - /*
description: |
    This library implements an EGL External Platform interface to work along with EGL drivers that support the external platform mechanism.
install    : |
    install -D -m 00644 eglexternalplatform.pc $installdir/%libdir%/pkgconfig/eglexternalplatform.pc
    install -D -d -m 00755 $installdir/usr/include/EGL
    install -m 00644 interface/*.h $installdir/usr/include/EGL/.
